### ISSUE TITLE
Unable to find helper

### ISSUE THREAD

**Issue by jme783** [losttype/metalsmith-register-helpers#1]
Hi there,

Trying to use your plugin but having some trouble having Handlebars recognize the helper I'm trying to register. I'm combining this with [metalsmith-templates](https://github.com/segmentio/metalsmith-templates) and hoping to register some helpers available in my `.hbs` files.

Here is the error: 
```
Error: Missing helper: 'contains'
    at new Error (<anonymous>)
    at Error.Exception (/Users/Jeff/Documents/particle-apps/docs/node_modules/handlebars/dist/cjs/handlebars/exception.js:13:41)
    at Object.<anonymous> (/Users/Jeff/Documents/particle-apps/docs/node_modules/handlebars/dist/cjs/handlebars/base.js:66:13)
    at Object.eval (eval at <anonymous> (/Users/Jeff/Documents/particle-apps/docs/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:171:23), <anonymous>:7:80)
    at ret (/Users/Jeff/Documents/particle-apps/docs/node_modules/handlebars/dist/cjs/handlebars/runtime.js:137:30)
    at ret (/Users/Jeff/Documents/particle-apps/docs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:422:21)
    at Function.exports.handlebars.render (/Users/Jeff/Documents/particle-apps/docs/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:497:14)
    at /Users/Jeff/Documents/particle-apps/docs/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:146:25
    at /Users/Jeff/Documents/particle-apps/docs/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:272:14
    at Object.oncomplete (fs.js:108:15)
```

Here is the relevant part of my `metalsmith.js` file:
```
    .use(helpers({
      directory: '../templates/helpers'
    }))
    .use(templates({
      engine: 'handlebars',
      directory: '../templates'
    }))
```

In my `templates/helpers` directory, I have a file called `contains.js`:

```
module.exports = function( collection, item, options ){
  // string check
  if( typeof collection === 'string' ){
    if( collection.search( item ) >= 0 ){
      return options.fn(this);
    }
    else {
      return options.inverse(this);
    }
  }
  // "collection" check (objects & arrays)
  for( var prop in collection ){
    if( collection.hasOwnProperty( prop ) ){
      if( collection[prop] == item ) return options.fn(this);
    }
  }
  return options.inverse(this);
};
```

and in my template:
```
  {{#contains path.href 'guide'}}
    Contains guide!
  {{else}}
    nope
  {{/contains}}
```

I would think that all of the pieces are in place to get this to work, but am having issues. Any ideas?

**Comment by revolunet** [comment]
is handlebars incompatible with this plugin ?

**Comment by kennethormandy** [comment]
No, I think the issue was that we had a conflicting version of Handlebars listed as a dependency. This plugin works with Handlebars and Metalsmith, we are still using it.

**Comment by revolunet** [comment]
cool thanks :+1:
